# Generated by Django 3.1.7 on 2021-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute',
            new_name='attribute_name',
        ),
        migrations.RenameField(
            model_name='context',
            old_name='context',
            new_name='context_name',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='individual',
            new_name='individual_name',
        ),
        migrations.AddField(
            model_name='ontology',
            name='ontology_name',
            field=models.CharField(default='test_ontology', max_length=30),
        ),
    ]
