# Generated by Django 3.1.7 on 2021-04-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210418_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Context',
            new_name='Concept',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='context_name',
            new_name='concept_name',
        ),
        migrations.RemoveField(
            model_name='ontology',
            name='contextes',
        ),
        migrations.AddField(
            model_name='ontology',
            name='concepts',
            field=models.ManyToManyField(to='mainpage.Concept'),
        ),
    ]
