# Generated by Django 3.1.7 on 2021-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210418_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attribute_value',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
