# Generated by Django 3.1.7 on 2021-04-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20210425_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubConcept2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_concept_name', models.CharField(max_length=30)),
                ('individuals', models.ManyToManyField(to='mainpage.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='SubConcept1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_concept_name', models.CharField(max_length=30)),
                ('individuals', models.ManyToManyField(to='mainpage.Individual')),
                ('sub_concepts2', models.ManyToManyField(to='mainpage.SubConcept2')),
            ],
        ),
        migrations.AddField(
            model_name='subconcept',
            name='sub_concepts1',
            field=models.ManyToManyField(to='mainpage.SubConcept1'),
        ),
    ]
